name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-solidity:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
    with:
      compareLcov: false
    secrets: inherit
  test-js:
    uses: bgd-labs/github-workflows/.github/workflows/test-node.yml@main
    if: github.event.pull_request.head.repo.full_name == github.repository
    secrets: inherit
